name: opencca build docker image
on:
#  push:
#    branches:
#     - main
# # release:
#   types: [published]
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  build:
    runs-on: [self-hosted, opencca]
    services:
      docker:
        image: docker:28-dind
        privileged: true
        options: --dns 8.8.8.8
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker CLI
        uses: docker/setup-docker-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image using Makefile
        run: make -f docker/Makefile release

      - name: Post build cleanup
        run: docker system prune -f

