name: Release docker container in registry

on:
#  push:
#    branches:
#     - main
# # release:
#   types: [published]
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  build:
    runs-on: [opencca]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date -u +%Y-%m-%dT%H:%M:%SZ)"

      - name: Build Docker image using Makefile
        run: make -f docker/Makefile release

      - name: Post build cleanup
        run: docker system prune -f